### ISSUE TITLE
I am trying to use VGGFace with resnet50, but with smaller image dimensions, I was wondering how can I do this without re-training the model from scratch...

### ISSUE THREAD

**Issue by TheStoneMX** [rcmalli/keras-vggface#52] opened 2019-06-26 21:12 UTC
**Please run this code and share your library versions**

```python
import tensorflow as tf
import keras
import keras_vggface

print(tf.__version__)
print(keras.__version__)
print(keras_vggface.__version__)

Using TensorFlow backend.
1.13.1
2.2.4
0.5

**Bug reports:**

Please replace this line with a brief summary of your issue AND if reporting a build issue include the link from:

**Code Sample:**

```
I am trying to use VGGFace with resnet50, but with smaller image dimensions, I was wondering how can I do this without re-training the model from scratch...

```python

base_model = VGGFace(model='resnet50', include_top=False, inputshape=(96, 96, 3))

**Error**
Negative dimension size caused by subtracting 7 from 3 for 'vggface_resnet50/avg_pool/AvgPool' (op: 'AvgPool') with input shapes: [?,3,3,2048].

```

**Comment by rcmalli** [comment] 2019-07-22 19:10
The input size was not supported as low as 96x96. Now it should be fixed.

**Closed by rcmalli** 2019-07-22 19:10 UTC

**Comment by werlang** [comment] 2019-09-10 16:22
Same error ocurred to me when fine tuning:

VGGFace(model='resnet50', include_top=False, input_shape=(112, 112, 3))

ERROR:
ValueError: Negative dimension size caused by subtracting 7 from 4 for 'avg_pool_2/AvgPool' (op: 'AvgPool') with input shapes: [?,4,4,2048].

**Comment by prathmeshrmadhu** [comment] 2019-12-04 13:33
> The input size was not supported as low as 96x96. Now it should be fixed.

Hello, @rcmalli I am also getting the same error as werlang. Could you please comment, if there is something that we could be possibly missing?

**Comment by sherlockchou86** [comment] 2020-04-23 06:48
If you use smaller input shape, maybe we need decrease the number of CNN layers in networks accordingly.
Because Conv2D or Average/MaxPooling layers will reduce the dims of features map, if the input shape is too small, there is no space/data for those layers to operate.

**Comment by annemacena** [comment] 2022-05-05 15:06
> 

Any thoughts about it?

> Same error ocurred to me when fine tuning:
> 
> VGGFace(model='resnet50', include_top=False, input_shape=(112, 112, 3))
> 
> ERROR: ValueError: Negative dimension size caused by subtracting 7 from 4 for 'avg_pool_2/AvgPool' (op: 'AvgPool') with input shapes: [?,4,4,2048].
> 
> tf version 1.14.0 keras version 2.2.0 vggface version 0.6
